=== MitchellDoesCoding/Yes-The-Other-Left/data/annotations/skindeep_mask_annotations.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "SkinDeep-542 inference-time mask annotations",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["image_id", "mask_preset", "right_mask_pct", "bottom_mask_pct", "mask_color"],
    "properties": {
      "image_id": {"type": "string", "pattern": "^DLB_[0-9]{8}$"},
      "filename": {"type": "string"},
      "manifest_master_filename": {"type": "string"},
      "mask_preset": {"enum": ["none", "bottom", "right", "both"]},
      "right_mask_pct": {"type": "number", "minimum": 0, "maximum": 100},
      "bottom_mask_pct": {"type": "number", "minimum": 0, "maximum": 100},
      "mask_color": {"enum": ["neutral_gray", "black", "white"]},
      "artifact_location": {"type": "string"},
      "annotation_complete": {"type": ["string", "boolean"]}
    },
    "additionalProperties": true
  }
}

=== MitchellDoesCoding/Yes-The-Other-Left/data/annotations/skindeep_mask_annotations_export.json
[
  {
    "image_id": "DLB_00011822",
    "filename": "images/DLB_00011822.jpg",
    "manifest_master_filename": "DLB_00011822.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011823",
    "filename": "images/DLB_00011823.jpg",
    "manifest_master_filename": "DLB_00011823.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011824",
    "filename": "images/DLB_00011824.jpg",
    "manifest_master_filename": "DLB_00011824.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011825",
    "filename": "images/DLB_00011825.jpg",
    "manifest_master_filename": "DLB_00011825.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011826",
    "filename": "images/DLB_00011826.jpg",
    "manifest_master_filename": "DLB_00011826.jpg",
    "mask_preset": "right",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011827",
    "filename": "images/DLB_00011827.jpg",
    "manifest_master_filename": "DLB_00011827.jpg",
    "mask_preset": "right",
    "right_mask_pct": 18,
    "bottom_mask_pct": 34,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011828",
    "filename": "images/DLB_00011828.jpg",
    "manifest_master_filename": "DLB_00011828.jpg",
    "mask_preset": "right",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011829",
    "filename": "images/DLB_00011829.jpg",
    "manifest_master_filename": "DLB_00011829.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011830",
    "filename": "images/DLB_00011830.jpg",
    "manifest_master_filename": "DLB_00011830.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011831",
    "filename": "images/DLB_00011831.jpg",
    "manifest_master_filename": "DLB_00011831.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011832",
    "filename": "images/DLB_00011832.jpg",
    "manifest_master_filename": "DLB_00011832.jpg",
    "mask_preset": "right",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011833",
    "filename": "images/DLB_00011833.jpg",
    "manifest_master_filename": "DLB_00011833.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011834",
    "filename": "images/DLB_00011834.jpg",
    "manifest_master_filename": "DLB_00011834.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011835",
    "filename": "images/DLB_00011835.jpg",
    "manifest_master_filename": "DLB_00011835.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011836",
    "filename": "images/DLB_00011836.jpg",
    "manifest_master_filename": "DLB_00011836.jpg",
    "mask_preset": "right",
    "right_mask_pct": 15,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011837",
    "filename": "images/DLB_00011837.jpg",
    "manifest_master_filename": "DLB_00011837.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011838",
    "filename": "images/DLB_00011838.jpg",
    "manifest_master_filename": "DLB_00011838.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011839",
    "filename": "images/DLB_00011839.jpg",
    "manifest_master_filename": "DLB_00011839.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011840",
    "filename": "images/DLB_00011840.jpg",
    "manifest_master_filename": "DLB_00011840.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011841",
    "filename": "images/DLB_00011841.jpg",
    "manifest_master_filename": "DLB_00011841.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011842",
    "filename": "images/DLB_00011842.jpg",
    "manifest_master_filename": "DLB_00011842.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011843",
    "filename": "images/DLB_00011843.jpg",
    "manifest_master_filename": "DLB_00011843.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011844",
    "filename": "images/DLB_00011844.jpg",
    "manifest_master_filename": "DLB_00011844.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011845",
    "filename": "images/DLB_00011845.jpg",
    "manifest_master_filename": "DLB_00011845.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011846",
    "filename": "images/DLB_00011846.jpg",
    "manifest_master_filename": "DLB_00011846.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011847",
    "filename": "images/DLB_00011847.jpg",
    "manifest_master_filename": "DLB_00011847.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011848",
    "filename": "images/DLB_00011848.jpg",
    "manifest_master_filename": "DLB_00011848.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011849",
    "filename": "images/DLB_00011849.jpg",
    "manifest_master_filename": "DLB_00011849.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011850",
    "filename": "images/DLB_00011850.jpg",
    "manifest_master_filename": "DLB_00011850.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011851",
    "filename": "images/DLB_00011851.jpg",
    "manifest_master_filename": "DLB_00011851.jpg",
    "mask_preset": "right",
    "right_mask_pct": 14,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011852",
    "filename": "images/DLB_00011852.jpg",
    "manifest_master_filename": "DLB_00011852.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011853",
    "filename": "images/DLB_00011853.jpg",
    "manifest_master_filename": "DLB_00011853.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011854",
    "filename": "images/DLB_00011854.jpg",
    "manifest_master_filename": "DLB_00011854.jpg",
    "mask_preset": "right",
    "right_mask_pct": 14,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011855",
    "filename": "images/DLB_00011855.jpg",
    "manifest_master_filename": "DLB_00011855.jpg",
    "mask_preset": "right",
    "right_mask_pct": 14,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
    "image_id": "DLB_00011856",
    "filename": "images/DLB_00011856.jpg",
    "manifest_master_filename": "DLB_00011856.jpg",
    "mask_preset": "bottom",
    "right_mask_pct": 18,
    "bottom_mask_pct": 20,
    "mask_color": "neutral_gray",
    "annotation_complete": "YES"
  },
  {
